### ISSUE TITLE
Incorect parsing of an existing SVG file

### ISSUE THREAD

**Issue by virresh** [alorence/pysvg-py3#3]
The capitalization code in parser is incorrect due to which no SVG file is read correctly and the try except is masking the actual error
https://github.com/alorence/pysvg-py3/blob/master/pysvg/parser.py#L42

Furthermore many times the parser creates a text object for newlines inside SVG source code which is pretty annoying:
https://github.com/alorence/pysvg-py3/blob/master/pysvg/parser.py#L55

**Comment by alorence** [comment]
Thanks foryour contribution. Since it is the first to clearly modfy original lib and adapt it to work well on Python 3, I need to update README before publishing a new release. I will upate on this thread to inform you when it is done.
Best regards

**Comment by alorence** [comment]
A new version 0.2.2-post3 has just been [published on Pypi](https://pypi.org/project/pysvg-py3/). It contains your patch as well as an updated description.
Thanks again for your contribution
