### ISSUE TITLE
Please use git tags for releases

### ISSUE THREAD

**Issue by davidak** [alorence/pysvg-py3#5]
so we can package it

use same version as on pypi

e.g. `0.2.2-post3` for https://github.com/alorence/pysvg-py3/commit/225e6f2b0145d9972bfec3c81d47735e055cf19f

i have to use github as source because pypi does not include the sample and i want to use it for automatic tests

**Comment by alorence** [comment]
Done. 2 tags have just been pushed to match current versions on Pypi
